---
- hosts: 10.0.0.5
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a directory
    file:
      path: /home/mohan88/myfolder
      state: directory
    
  - name: copy static file
    copy:
      src: mystaticfile
      dest: /home/mohan88/myfolder/mystaticfile

  - name: download internet files
    get_url:
      url: https://github.com/iam-veeramalla/Azure-zero-to-hero/blob/main/Day-01/01-basics.md
      dest: /home/mohan88/myfolder/mystaticfile
      force_basic_auth: yes

  - name: i want to install apache2 webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy index file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html