---
- hosts: all
  become: yes
  tasks:
    - name: install git (apt-get install git)
      apt:
        name: apache2
        state: present
    - name: install tree (apt-get install tree)
      apt:
        name: tree
        state: present
    - name: install wget (apt-get install wget)
      apt:
        name: wget
        state: present


