---
- hosts: 10.0.0.5
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a directory
    file:
      path: /home/mohan88/myfolder
      state: directory
    
  - name: copy static file
    copy:
      src: mystaticfile
      dest: /home/mohan88/myfolder/mystaticfile

  - name: download internet files
    get_url:
      url: http://example.com/path/file.conf
      dest: /home/mohan88/myfolder/mystaticfile
      force_basic_auth: yes